apiVersion: autoscaling.k8s.io/v1beta2
kind: VerticalPodAutoscaler
metadata:
  name: vpa-mqtt-offf
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind: Deployment
    name: hivemq
  updatePolicy:
    updateMode: "Off"
#  resourcePolicy:
#    containerPolicies:
#      - containerName: '*'
#        minAllowed:
#          cpu: 500m
#          memory: 1024Mi
#        maxAllowed:
#           cpu: 2000m
#           memory: 4096Mi

