apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: hivemq
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: mqttserver.local
    http:
      paths:
      - path: /
        backend:
          serviceName: hivemq-hivemq-mqtt
          servicePort: 1883
  
